### PR TITLE
use graceful-fs instead of fs

### PR DESCRIPTION
**Pull request by continuata**
`graceful-fs` improves a bunch of things in `fs` and is a drop-in replacement.

https://github.com/isaacs/node-graceful-fs

### CODE REVIEW

**Comment by tusharmath** [comment]
Is there anything that is relevant to this module that graceful-fs is
solving?

On Sun, Mar 13, 2016, 12:35 AM Stu Kennedy <notifications@github.com> wrote:

> graceful-fs improves a bunch of things in fs and is a drop-in replacement.
>
> https://github.com/isaacs/node-graceful-fs
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/tusharmath/Multi-threaded-downloader/pull/65
> Commit Summary
>
>    - use graceful-fs instead of fs
>
> File Changes
>
>    - *M* package.json
>    <https://github.com/tusharmath/Multi-threaded-downloader/pull/65/files#diff-0>
>    (1)
>    - *M* src/observables.js
>    <https://github.com/tusharmath/Multi-threaded-downloader/pull/65/files#diff-1>
>    (2)
>
> Patch Links:
>
>    - https://github.com/tusharmath/Multi-threaded-downloader/pull/65.patch
>    - https://github.com/tusharmath/Multi-threaded-downloader/pull/65.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tusharmath/Multi-threaded-downloader/pull/65>.
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by continuata** [comment]
Here's the main list of improvements over fs

- Queues up open and readdir calls, and retries them once something closes if there is an EMFILE error from too many file descriptors.
- fixes lchmod for Node versions prior to 0.6.2.
- implements fs.lutimes if possible. Otherwise it becomes a noop.
- ignores EINVAL and EPERM errors in chown, fchown or lchown if the user isn't root.
- makes lchmod and lchown become noops, if not available.
- retries reading a file if read results in EAGAIN error.

On Windows, it retries renaming a file for up to one second if EACCESS or EPERM error occurs, likely because antivirus software has locked the directory.

It seems to perform better for concurrent writing processes (which mt-downloader obviously does)

Another download manager app developer has put graceful-fs under load testing over the last few months and they put me onto it as a marked improvement for multi-threaded downloading, this is why I'm suggesting you switch to using it over standard fs.

**Comment by tusharmath** [comment]
Got it. Take a look at the contribution guide lines — https://github.com/tusharmath/Multi-threaded-downloader/blob/master/README.md#contribution-guidelines

- [ ] git `reword` the commit to `<type>(<scope>): <subject>` format.
- [ ] back merge from master

**Comment by continuata** [comment]
ok ready for you

**Comment by tusharmath** [comment]
Thanks! Added you to the list of collaborators so that you can make changes directly in future.

**Pull request merged**
