### PR TITLE
Fallback mechanism for downloads of unknown sizes

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by tusharmath** [comment]
@continuata this would most probably fix #66. Let me know if you are able to download then stop and then resume.

**Comment by continuata** [comment]
great ... will try it out later when I'm back in.

**Comment by continuata** [comment]
that doesn't work for me.
I still get a 0 sized download, even if I only use one thread.
Is it using the size returned from the initial header to truncate it or something like that?

**Comment by tusharmath** [comment]
Yup. This wouldn't be the right solution.

**Pull request closed without merging**
